python NetworkEpiScript.py -i 0.   &
python NetworkEpiScript.py -i 0.1  &
python NetworkEpiScript.py -i 0.14 &
python NetworkEpiScript.py -i 0.2  &
python NetworkEpiScript.py -i 0.3  &
python NetworkEpiScript.py -i 0.4  &
python NetworkEpiScript.py -i 0.6  &
python NetworkEpiScript.py -i 0.9  &
python NetworkEpiScript.py -i 1.3  &
python NetworkEpiScript.py -i 1.8  &
python NetworkEpiScript.py -i 2.6  &
python NetworkEpiScript.py -i 3.8  &
python NetworkEpiScript.py -i 5.5  &
python NetworkEpiScript.py -i 7.8  &
python NetworkEpiScript.py -i 11.  &
python NetworkEpiScript.py -i 16.  &
python NetworkEpiScript.py -i 23.  &
python NetworkEpiScript.py -i 33.  &
python NetworkEpiScript.py -i 48.  &
python NetworkEpiScript.py -i 69.  &
python NetworkEpiScript.py -i 100. &
