python NetworkEpiScript.py -i 0.00 &
python NetworkEpiScript.py -i 0.10 &
python NetworkEpiScript.py -i 0.13 &
python NetworkEpiScript.py -i 0.18 &
python NetworkEpiScript.py -i 0.24 &
python NetworkEpiScript.py -i 0.33 &
python NetworkEpiScript.py -i 0.44 &
python NetworkEpiScript.py -i 0.59 &
python NetworkEpiScript.py -i 0.80 &
python NetworkEpiScript.py -i 1.08 &
python NetworkEpiScript.py -i 1.45 &
python NetworkEpiScript.py -i 1.95 &
python NetworkEpiScript.py -i 2.63 &
python NetworkEpiScript.py -i 3.53 &
python NetworkEpiScript.py -i 4.76 &
python NetworkEpiScript.py -i 6.40 &
python NetworkEpiScript.py -i 8.62 &
python NetworkEpiScript.py -i 11.6 &
python NetworkEpiScript.py -i 15.6 &
python NetworkEpiScript.py -i 21.0 &
python NetworkEpiScript.py -i 28.2 &
python NetworkEpiScript.py -i 38.0 &
python NetworkEpiScript.py -i 51.2 &
python NetworkEpiScript.py -i 68.9 &
python NetworkEpiScript.py -i 92.8 &
python NetworkEpiScript.py -i 124  &
python NetworkEpiScript.py -i 168  &
#python NetworkEpiScript.py -i 226  &
#python NetworkEpiScript.py -i 304  &
#python NetworkEpiScript.py -i 410  &
#python NetworkEpiScript.py -i 551  &
#python NetworkEpiScript.py -i 742  &
#python NetworkEpiScript.py -i 1000 &
